### ISSUE TITLE
Python-based app fails to start

### ISSUE THREAD

**Issue by gilzow** [ddev/ddev-platformsh#116]
Per request from @rfay submitting this ticket
After running through config and adding the integration, `ddev start` / `ddev restart` fails with 
```
Failed to get project(s): unsupported PHP version: python:3.11, ddev only supports the following versions: [5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1 8.2]

```

[Project repository](https://github.com/gilzow/Platformify_Flask_Cookies)
[Terminal output for setup](https://gist.github.com/gilzow/ba0b1a7ad2875bd2a8d542f5951206e8)
```
❯ ddev --version
ddev version v1.22.1
```
`.ddev/config.yaml`
```
name: platformify-cookies-app
type: python
docroot: ""
php_version: "8.1"
webserver_type: nginx-gunicorn
```
`.ddev/config.platformsh.yaml`
```
# #ddev-generated
# Generated configuration based on platform.sh project configuration
disable_settings_management: true

php_version: python:3.11
```

**Comment by rfay** [comment]
Thanks for this issue!

`ddev-platformsh` currently supports only projects of type `php`, even though DDEV itself has experimental support for `python`, etc. 

* #117
Adds a test to make sure people are trying `php` and adds that info to the README.

**Comment by gilzow** [comment]
🖖
