### ISSUE TITLE
There are no commands defined in the "self" namespace.

### ISSUE THREAD

**Issue by stasadev** [ddev/ddev-platformsh#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

From Discord https://discord.com/channels/664580571770388500/1068592266752573440/1246171053257003032

### Expected Behavior

After switching to go-based platform.sh CLI binary in

- https://github.com/ddev/ddev/pull/5995

https://github.com/ddev/ddev-platformsh/blob/c82eabc5ae960ebe11c965bdface8f75978ff0f0/install.yaml#L295-L297

The hook should be updated with:

```
(sudo apt-get update &>/dev/null || true) && (sudo apt-get install -y platformsh-cli &>/dev/null || true)
```

And a new restriction for DDEV v1.23.0+ should be added.

Or maybe that update line should be simply removed.

### Actual Behavior

```
platform self:update -qy --no-major || true

  [CommandNotFoundException]                              
  There are no commands defined in the "self" namespace.
```

### Steps To Reproduce

Use the latest DDEV with this add-on, run `ddev start`.

**Comment by rfay** [comment]
IMO we just shouldn't be doing an upgrade.

If one were to be done, it should be in a .ddev/web-build/Dockerfile, rather than in post-start hook.
