### ISSUE TITLE
Environment variables must be set much earlier for php-fpm

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-platformsh#89]
@gilzow and I were working on ddev.com site today, trying to use this add-on with it, and it turned out that the environment variables it needs to operate didn't get set early enough to be used by php-fpm. 

What we do currently is create https://github.com/drud/ddev-platformsh/blob/main/homeadditions/.bashrc.d/platformsh-environment.sh, which loads environment variables in bash based on .global/environment and .environment.

Some things we could do instead:

1. Create a .ddev/.env with these same environment variables (but that could overwrite user info) or
2. Create a `docker-compose.platformsh.yaml` that set them with an `environment` section.

Both of these are pretty easy.

**Comment by rfay** [comment]
I didn't realize that .environment was a free-form file, like https://github.com/drud/ddevdotcom/blob/main/.environment

```
export DB_NAME=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".database[0].path")
export DB_HOST=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".database[0].host")
export DB_PORT=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".database[0].port")
export DB_USER=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".database[0].username")
export DB_PASSWORD=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".database[0].password")

export WP_HOME=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select(.value.primary == true) | .key')
export WP_SITEURL="${WP_HOME}wp"
export WP_DEBUG_LOG=/var/log/app.log
export WP_ENV="${PLATFORM_ENVIRONMENT_TYPE}"
export AUTH_KEY=$PLATFORM_PROJECT_ENTROPY
export SECURE_AUTH_KEY=$PLATFORM_PROJECT_ENTROPY
export LOGGED_IN_KEY=$PLATFORM_PROJECT_ENTROPY
export NONCE_KEY=$PLATFORM_PROJECT_ENTROPY
export AUTH_SALT=$PLATFORM_PROJECT_ENTROPY
export SECURE_AUTH_SALT=$PLATFORM_PROJECT_ENTROPY
export LOGGED_IN_SALT=$PLATFORM_PROJECT_ENTROPY
export NONCE_SALT=$PLATFORM_PROJECT_ENTROPY
```

**Comment by rfay** [comment]
We already add a number of environment variables to config.platformsh.yaml, but they're static environment variables, not free-form bash stuff.

**Comment by gilzow** [comment]
And unfortunately, we have numerous templates that rely on the `.environment` file to translate `PLATFORM_*` environmental variables into needed environmental variables needed to run correctly:

* [Akeneo](https://github.com/platformsh-templates/akeneo/blob/master/.environment)
* [Directus](https://github.com/platformsh-templates/directus/blob/master/.environment)
* [Elastic](https://github.com/platformsh-templates/elastic-apm/blob/master/kibana/.environment) [APM](https://github.com/platformsh-templates/elastic-apm/blob/master/apm/.environment) (might not be relevant for DDEV but am including to be thorough) 
* [Flask](https://github.com/platformsh-templates/flask/blob/master/.environment)
* [Mattermost](https://github.com/platformsh-templates/mattermost/blob/master/.environment)
* [Spring Boot Gradle](https://github.com/platformsh-templates/spring-boot-gradle-mysql/blob/master/.environment)
* [Spring MVC Maven MongoDB](https://github.com/platformsh-templates/spring-mvc-maven-mongodb/blob/master/.environment)
* [Spring Boot Maven MySQL](https://github.com/platformsh-templates/spring-boot-maven-mysql/blob/master/.environment)
* [Spring Kotlin](https://github.com/platformsh-templates/spring-kotlin/blob/master/.environment)
* [WordPress Bedrock](https://github.com/platformsh-templates/wordpress-bedrock/blob/master/.environment) (which DDEV.com uses)
* [WordPress Vanilla](https://github.com/platformsh-templates/wordpress-vanilla/blob/master/.environment)
* [WordPress WooCommerce](https://github.com/platformsh-templates/wordpress-woocommerce/blob/master/.environment)
* [WordPress NextJS](https://github.com/platformsh-templates/nextjs-wordpress/blob/main/api/.environment)

The Drupal templates [also use](https://github.com/platformsh-templates/drupal9/blob/master/.environment) an `.environment` file, but only to add the composer bin directory to `PATH`

**Comment by rfay** [comment]
> The Drupal templates [also use](https://github.com/platformsh-templates/drupal9/blob/master/.environment) an .environment file, but only to add the composer bin directory to PATH

And of course composer is already provided by DDEV and is already in the $PATH

**Comment by gilzow** [comment]
Looks like I missed a few in my initial scan

* [Django4](https://github.com/platformsh-templates/django4/blob/master/.environment) (used to add to `PATH`)
* [Eleventy](https://github.com/platformsh-templates/eleventy-strapi/blob/master/eleventy/.environment) [Strapi](https://github.com/platformsh-templates/eleventy-strapi/blob/master/strapi/.environment)
* [Strapi4](https://github.com/platformsh-templates/strapi4/blob/master/.environment)

**Comment by rfay** [comment]
This problem also points out the poverty of the tests. Currently I think all the tests just do a `ddev start` and call it good if that works out. But the reality is they need to have real databases and see if they can get real content. And that means slower tests and it means we need to figure out a way to have minimal content available.

**Comment by rfay** [comment]
A way to do this that would be general (but likely require changes to DDEV):
* https://github.com/drud/ddev/issues/4233
